version: '3'
services:
  mongodb-playground:
    image: mongo
    container_name: mongodb-playground
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
