version: '3'
services:
  mongodb-playground:
    image: mongo
    container_name: mongodb-playground
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  test-e2e-db:
    image: mongo
    container_name: test-e2e-db
    ports:
      - '27018:27017'

  test-watch:
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - .:/project

volumes:
  mongodb_data:
