version: '3'
services:
  dev-db:
    image: mongo
    container_name: dev-db
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  test-e2e-db:
    image: mongo
    container_name: test-e2e-db
    ports:
      - '27018:27017'

  test-unit:
    build:
      context: .
      dockerfile: test.Dockerfile
    container_name: test-unit
    volumes:
      - .:/project

volumes:
  mongodb_data:
